version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  app-android:
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - checkout
      - run:
          name: Decoding and writing the Keystore file
          command: base64 -d \<<< "${RELEASE_KEYSTORE_BASE64}" > ./android/keystore
      - run:
          name: Building the Android App
          command: |
            export GIT_COMMIT_DESC="$(git log --format=format:%s -n 1 $CIRCLE_SHA1 | sed 's/\"//g')"
            echo GIT_COMMIT_DESC="$GIT_COMMIT_DESC"
            if [[ GIT_COMMIT_DESC == "Update README.md" ]]; then
              cd android && ./gradlew clean && ./gradlew bundleRelease
            fi
      - store_artifacts:
          path: android/app/build/outputs/bundle/release/app-release.aab

workflows:
  app-builder:
    jobs:
      - app-android:
          filters:
            branches:
              only: main # Commits to main branch
