version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  android-app:
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - checkout
      - run:
          name: Building Android App
          command: cd android && ./gradlew clean && ./gradlew bundleRelease
      - store_artifacts:
          path: android/app/build/outputs/aab/release/app-release-unsigned.aab

workflows:
  building-apps:
    jobs:
      - android-app:
          filters:
            branches:
              only: main # Commits to main branch
