name: App Builder Android

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up the environment 
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Decoding and writing the Keystore file
        run: echo ${{ secrets.KEYSTORE }} | base64 -di > android/keystore
      - name: Making Gradlew executable
        run: chmod +x ./android/gradlew
      - name: Building the Android App Bundle
        run: cd android && ./gradlew clean && ./gradlew bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Attaching the Android App Bundle to this workflow
        uses: actions/upload-artifact@v2
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/app-release.aab
      - name: Building the Android App APK
        run: cd android && ./gradlew clean && ./gradlew assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Attaching the Android App APK to this workflow
        uses: actions/upload-artifact@v2
        with:
          name: app-release-apk
          path: android/app/build/outputs/release/release/app-release.apk
